---
title: "Make RDS"
author: "Casey Crary"
date: "2024-03-31"
date-format: iso
format: pdf
editor: source
---

```{r}
#| label: setup
#| include: false
#library(unsure)
```

This file takes all the data from "data-raw-depaginate" (which will be changed to "data-raw-dehyphenate"), and appends all the txt files into one.  Aspirational goal:  make this output an rds file instead.  

```{r}
write("", "data/output.txt")        # create file to output to

# appends a given chapter_name onto output.txt
append_chapter <- function(chapter_name) {
  to_write_to <- "data/output.txt"
  file_name <- paste0("data-raw-depaginate/", chapter_name, ".txt")
  chap_data <- readLines(file_name)

  write(chap_data,file=to_write_to,append=TRUE)
  write("\n", file=to_write_to, append = TRUE)
  
  return(NULL)
}

# does so for all chapters (NOT appendix, needs to be added somehow)
for(i in 0:28) {
  chapter_num <- sprintf("%02d", i)
  chapter_name <- paste("chapter", chapter_num, "_cleaned", sep="")
  
  append_chapter(chapter_name)
}

# proof we can then put output.txt into an R object
HistoryAmherstCollege <- readLines("data/output.txt")


# makes tibble with line number and chapter number
hac_tibble <- HistoryAmherstCollege |> tibble()

hac_tibble_mod <- hac_tibble |>
  rename(text = HistoryAmherstCollege) |>
  mutate(linenumber = row_number(),
         chapter = cumsum(
                  str_detect(text,
                             regex("^CHAPTER [\\DIVXLC]+",
                             ignore_case = FALSE))
                  )
         )
hac_tibble_mod

# usethis::use_data(HistoryAmherstCollege, overwrite = TRUE)
```




