project:
  type: website
  output-dir: ../docs
  
website: 
  title: "The History of Amherst College (Tyler, 1873)"
  navbar:
    left: 
      -  href: index.qmd
         text: Home
      -  href: book_info.qmd
         text: Book info
      -  href: example_text.qmd
         text: Example text
      -  href: example_analysis.qmd
         text: Example analysis
      -  href: data_package.qmd
         text: Data package
    
format:
  html:
    theme: cosmo
    css: styles.css
