project:
  type: website
  output-dir: docs
  
website: 
  title: "The History of Amherst College"
  navbar:
    left: 
      -  href: index.qmd
         text: Home
      -  href: book_info.qmd
         text: Book Info
      -  href: example_text.qmd
         text: Example Text
      -  href: example_analysis.qmd
         text: Example Analysis
    
format:
  html:
    theme: cosmo
    css: styles.css