---
title: "The History of Amherst College"
page-layout: full
title-block-banner: true
format:
  html:
    toc: true
    toc-location: left
    
---
# Background
This website provides the text and analysis of William Seymour Tyler's _History of Amherst College during its first half century, 1821-1871_. 

Click [here](https://archive.org/details/historyofamherst00tyleiala) to see the book in a variety of formats.
As part of this project, we processed the scanned-in text version of book to create a more clean and organized form that is available as an [R package](data_package.qmd).
See [here](https://github.com/STAT325-S24/HistoryAmherstCollege) for the raw text and routines to process it.

The [Book Info Tab](book_info.qmd) gives more information about the publication of the book.

# Explore the text
Use the [Example Text Tab](example_text.qmd) to see some examples of the cleaned text as well as an example of the Table of Contents.

# Sample Analysis
Use the [Example Analysis Tab](example_analysis.qmd) to explore a sample analysis of the book. 

# Amherst College
More information about Amherst College can be found [here](https://amherst.edu).

Last updated 2024-04-14.
